variables:
  CI_TARGET_BUILD_DEPENDS: ubus
  CI_CMAKE_EXTRA_BUILD_ARGS: -DLUAPATH=/usr/lib/lua

include:
  - remote: https://gitlab.com/ynezz/openwrt-ci/raw/master/openwrt-ci/gitlab/main.yml
  - remote: https://gitlab.com/ynezz/openwrt-ci/raw/master/openwrt-ci/gitlab/pipeline.yml
